### ISSUE TITLE
ubuntu 22.04

### ISSUE THREAD

**Issue by lucasw** [lucasw/dynamic_reconfigure_tools#18]
Need `setValue()` cast values to int where appropirate- new python checks types more.

```
  File "/home/lucasw/catkin_ws/src/lucasw/dynamic_reconfigure_tools/rqt_dr_single/src/rqt_dr_single/dr_single.py", line 260, in update_description
    widget.setValue(slider_val)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```

Also
```
[ERROR] [1651934929.309268 /rqt_gui_py_node_13391 /home/lucasw/catkin_ws/src/lucasw/dynamic_reconfigure_tools/rqt_dr_single/src/rqt_dr_single/dr_single.py:482]: 'Thread' object has no attribute 'isAlive'
```

-> `is_alive()` should work in 20.04 also https://github.com/fkie/multimaster_fkie/issues/149

Following on from https://github.com/lucasw/ros_from_src/issues/6
